# Tensors

In [65]:
import torch
import numpy as np

In [66]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [67]:
data_1 = np.array(data)
x_np = torch.from_numpy(data_1)
x_np

tensor([[1, 2],
        [3, 4]])

In [68]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1366, 0.8409],
        [0.8625, 0.1336]])


In [69]:
shape = (2,3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[[0.3980, 0.2787, 0.4255, 0.5686],
         [0.7490, 0.7051, 0.7702, 0.5904],
         [0.8491, 0.7447, 0.8384, 0.6197]],

        [[0.9172, 0.2699, 0.1902, 0.8269],
         [0.7966, 0.3968, 0.3407, 0.8892],
         [0.0502, 0.0208, 0.3442, 0.9181]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [70]:
tensor = torch.rand(3,4)

print("Shape:\t\t", tensor.shape)
print("Datatype:\t", tensor.dtype)
print("Stored on:\t", tensor.device)

Shape:		 torch.Size([3, 4])
Datatype:	 torch.float32
Stored on:	 cpu


Many Tensor operations are described on pytorch documentation [here](https://pytorch.org/docs/stable/torch.html)

In [73]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored on: {tensor.device}")
print(torch.cuda.is_available())


False


In [72]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
